services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ${PACKAGE_NAME}_dev_app
    platform: linux/amd64
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://root:root@mongodb:27017/${PACKAGE_NAME}_db?authSource=admin

      REDIS_HOST: redis-master
      REDIS_PORT: 6379

      BASE_URL: http://0.0.0.0:3000
      PORT: 3000
    ports:
      - '3000:3000'
    volumes:
      # Mount source code for live reload
      - ./src:/usr/src/app/src:cached
      - ./tsconfig.json:/usr/src/app/tsconfig.json:cached
      - ./nest-cli.json:/usr/src/app/nest-cli.json:cached

      # Keep node_modules in container
      - /usr/src/app/node_modules

      # Mount uploads and temp directories
      - ./uploads:/usr/src/app/uploads
      - ./temp:/usr/src/app/temp
    depends_on:
      mongodb:
        condition: service_healthy
      redis-master:
        condition: service_healthy
    command: >
      sh -c "
        echo '🏁 Waiting for MongoDB...';
        sleep 3;
        echo '🚀 Starting app in development mode with live reload...';
        pnpm dev
      "
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://0.0.0.0:3000/health']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongodb:
    image: mongo:8
    container_name: ${PACKAGE_NAME}_dev_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${PACKAGE_NAME}_db
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - dev_mongodb_data:/data/db
    ports:
      - '127.0.0.1:27017:27017'
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")']
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express
    container_name: ${PACKAGE_NAME}_dev_mongo_express
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_PASS}
    ports:
      - '8081:8081'
    depends_on:
      mongodb:
        condition: service_healthy

  redis-master:
    image: redis
    container_name: ${PACKAGE_NAME}_dev_redis
    command:
      [
        'redis-server',
        '--appendonly',
        'yes',
        '--bind',
        '0.0.0.0',
        '--protected-mode',
        'no',
      ]
    ports:
      - '22376:6379'
    volumes:
      - dev_redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  dev_mongodb_data:
  dev_redis_data:

networks:
  default:
    name: ${PACKAGE_NAME}_dev_network
    labels:
      - 'project=${PACKAGE_NAME}'
      - 'environment=development'
